openapi: 3.0.0
info:
  title: Single Assistant Chat API
  version: 1.0.0
  description: API for the unified single assistant that handles both chat and task management

paths:
  /api/{user_id}/chat:
    post:
      summary: Send message to the single assistant
      description: Process user message through the unified assistant that handles both general chat and task-specific operations
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
          description: The ID of the user sending the message
        - name: authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the single assistant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request (invalid user_id)
        '401':
          description: Unauthorized (invalid token)
        '403':
          description: Forbidden (user not authorized for this resource)
        '404':
          description: Conversation not found
        '422':
          description: Unprocessable entity (invalid request body)

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message
          minLength: 1
          maxLength: 1000
        conversation_id:
          type: integer
          minimum: 1
          description: Optional ID of existing conversation, omit for new conversation
      example:
        message: "Add a task to buy groceries"
        conversation_id: 123

    ChatResponse:
      type: object
      required:
        - conversation_id
        - response
        - message_id
      properties:
        conversation_id:
          type: integer
          description: ID of the conversation
        response:
          type: string
          description: Assistant's response to the user
        message_id:
          type: integer
          description: ID of the assistant's response message
        conversation_title:
          type: string
          description: Title of new conversation (only present when starting new conversation)
        has_tool_calls:
          type: boolean
          description: Whether the assistant performed any tool operations
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCallInfo'
      example:
        conversation_id: 123
        response: "Great! I've added the task 'buy groceries' to your list!"
        message_id: 456
        has_tool_calls: true
        tool_calls:
          - tool_name: add_task
            parameters:
              user_id: "1"
              title: "buy groceries"
            execution_status: executed

    ToolCallInfo:
      type: object
      required:
        - tool_name
        - parameters
      properties:
        tool_name:
          type: string
          description: Name of the MCP tool called
        parameters:
          type: object
          description: Parameters passed to the tool
        execution_status:
          type: string
          description: Status of tool execution (pending, executed, failed)
          enum: [pending, executed, failed]