openapi: 3.0.1
info:
  title: Chat API
  description: API for chat-based task management with single assistant
  version: 1.0.0
paths:
  /api/{user_id}/chat:
    post:
      summary: Send a message to the single assistant
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the user sending the message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from the single assistant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message
          maxLength: 1000
        conversation_id:
          type: integer
          description: ID of existing conversation, null for new conversation
          minimum: 1
      example:
        message: "Add a task to buy groceries"
        conversation_id: null
    ChatResponse:
      type: object
      required:
        - conversation_id
        - response
        - message_id
      properties:
        conversation_id:
          type: integer
          description: ID of the conversation
        response:
          type: string
          description: The assistant's response
        message_id:
          type: integer
          description: ID of the response message
        conversation_title:
          type: string
          description: Title of new conversation (null if existing conversation)
          nullable: true
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCallInfo'
        has_tool_calls:
          type: boolean
          description: Whether the response suggests potential tool usage
    ToolCallInfo:
      type: object
      properties:
        tool_name:
          type: string
          description: Name of the tool that might be called
        parameters:
          type: object
          description: Parameters for the potential tool call
        execution_status:
          type: string
          description: Status of tool execution (pending, executed, failed)
          nullable: true