openapi: 3.0.0
info:
  title: Conversation API
  version: 1.0.0
  description: API for conversation handling with intent detection and task management

paths:
  /api/conversation/clarify:
    post:
      summary: Process user input for clarification or task execution
      description: |
        Handles user messages by detecting intent and either responding conversationally
        or executing task management operations based on user request.

        Every request will return a text response regardless of intent.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
                  description: User's input message
                  example: "Add a task to buy groceries"
                message:
                  type: string
                  description: Alternative field for user's input message
                  example: "What can you do for me?"
                text:
                  type: string
                  description: Alternative field for user's input message
                  example: "Delete task #1"
                sessionId:
                  type: string
                  description: Session identifier for conversation context
                  example: "sess-12345"
                session_id:
                  type: string
                  description: Alternative field for session identifier
                  example: "sess-67890"
                context:
                  type: object
                  description: Additional context for the conversation
                  properties:
                    user_id:
                      type: string
                      description: User identifier
                      example: "user-123"
                  example:
                    user_id: "user-123"
                ctx:
                  type: object
                  description: Alternative field for context information
                  example:
                    user_id: "user-456"
              anyOf:
                - required: ["input"]
                - required: ["message"]
                - required: ["text"]
      responses:
        '200':
          description: Successful response with appropriate content
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseType:
                    type: string
                    enum: [success, clarification, error]
                    description: Type of response
                    example: "success"
                  message:
                    type: string
                    description: Text response to the user
                    example: "I have added the task 'buy groceries' to your list."
                  clarifyingQuestions:
                    type: array
                    items:
                      type: string
                    description: Questions to clarify user intent
                    example: ["To be clear: did you mean to buy groceries today or tomorrow?"]
                  suggestedActions:
                    type: array
                    items:
                      type: string
                    description: Suggested follow-up actions
                    example: ["Complete task #1", "Add deadline to task"]
                  conversationId:
                    type: string
                    description: Conversation identifier
                    nullable: true
                    example: "conv-12345"
                  analysis:
                    type: object
                    properties:
                      intent:
                        type: object
                        properties:
                          is_ambiguous:
                            type: boolean
                            example: false
                      ambiguity:
                        type: object
                        properties:
                          is_ambiguous:
                            type: boolean
                            example: false
                      vagueness:
                        type: object
                        properties:
                          is_vague:
                            type: boolean
                            example: false
                    example:
                      intent: {"is_ambiguous": false}
                      ambiguity: {"is_ambiguous": false}
                      vagueness: {"is_vague": false}
        '422':
          description: Unprocessable entity - required fields missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "input is required"

  /api/conversation/test:
    get:
      summary: Test endpoint to verify conversation router is working
      description: Simple endpoint to confirm the conversation router is properly registered
      responses:
        '200':
          description: Router is working
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  message:
                    type: string
                    example: "Conversation router is working!"

  /api/conversation/test-post:
    post:
      summary: Test POST endpoint to verify POST routes work
      description: Simple POST endpoint to confirm POST routes function on the conversation router
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              description: Optional data to test with
      responses:
        '200':
          description: POST route is working
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  message:
                    type: string
                    example: "Conversation router POST route is working!"
                  received_data:
                    type: object
                    description: Data received in the request
                    nullable: true